"""empty message

Revision ID: 0db3d88b0a50
Revises: 1ccc04d6c13a
Create Date: 2026-01-11 13:14:26.183540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db3d88b0a50'
down_revision: Union[str, Sequence[str], None] = '1ccc04d6c13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('vehicle', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('vehicle', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'lon')
    op.drop_column('vehicle', 'lat')
    op.drop_column('vehicle', 'name')
    # ### end Alembic commands ###
