"""start

Revision ID: 97c5b50d3d91
Revises: 316cd1d9077d
Create Date: 2026-01-10 22:04:37.395428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97c5b50d3d91'
down_revision: Union[str, Sequence[str], None] = '316cd1d9077d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('vtype', sa.String(length=32), nullable=False),
    sa.Column('vconfig', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('immobilized', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geofence_created',
    sa.Column('geofence_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.PrimaryKeyConstraint('geofence_id', 'ts')
    )
    op.create_table('geofence_deleted',
    sa.Column('geofence_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.PrimaryKeyConstraint('geofence_id', 'ts')
    )
    op.create_table('geofence_modified',
    sa.Column('geofence_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.PrimaryKeyConstraint('geofence_id', 'ts')
    )
    op.create_table('vehicle_created',
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'ts')
    )
    op.create_table('vehicle_deleted',
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'ts')
    )
    op.create_table('vehicle_geofence_event',
    sa.Column('geofence_id', sa.Uuid(), nullable=False),
    sa.Column('entered', sa.Boolean(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('geofence_id', 'vehicle_id', 'ts')
    )
    op.create_table('vehicle_immobilized',
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('geofence_id', sa.Uuid(), nullable=True),
    sa.Column('immobilized', sa.Boolean(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'ts')
    )
    op.create_table('vehicle_modified',
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'ts')
    )
    op.create_table('vehicle_pos',
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'ts')
    )
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_table('vehicle_pos')
    op.drop_table('vehicle_modified')
    op.drop_table('vehicle_immobilized')
    op.drop_table('vehicle_geofence_event')
    op.drop_table('vehicle_deleted')
    op.drop_table('vehicle_created')
    op.drop_table('geofence_modified')
    op.drop_table('geofence_deleted')
    op.drop_table('geofence_created')
    op.drop_table('vehicle')
    op.drop_table('geofence')
    # ### end Alembic commands ###
