"""empty message

Revision ID: b2432150cbcd
Revises: 97c5b50d3d91
Create Date: 2026-01-10 22:54:07.218518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2432150cbcd'
down_revision: Union[str, Sequence[str], None] = '97c5b50d3d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_geofence',
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('geofence_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'geofence_id')
    )
    op.add_column('geofence', sa.Column('immobilize_enter', sa.Boolean(), nullable=False))
    op.add_column('geofence', sa.Column('immobilize_leave', sa.Boolean(), nullable=False))
    op.alter_column('vehicle_modified', 'user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_modified', 'user_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('geofence', 'immobilize_leave')
    op.drop_column('geofence', 'immobilize_enter')
    op.drop_table('vehicle_geofence')
    # ### end Alembic commands ###
